### ISSUE TITLE
404 Error When leaving Review (profile image)

### ISSUE THREAD

**Issue by mrthomasjackson** [Arcrammer/Savannah#2]
If a user without a profile image creates a review, a 404 error occurs with no image (https://savannah.ullmannite.ml/images/users/undefined).

**Comment by Arcrammer** [comment]
Fixed in 58f653001883d058fe4492d1fe72083276da143b. Thank you for bringing that bug to my attention! No profile photo will show if the user who posted the review hasn't uploaded one yet. The same goes for seminar reviews.
